### ISSUE TITLE
Patch fails with ESP-IDF 4.4.2.

### ISSUE THREAD

**Issue by Hokoshi** [u-blox/u-blox-sho-OpenCPU#12]
Patch fails with ESP-IDF 4.4.2.
Could you make a patch for 4.4.2 ?

$ patch -p2 -i /c/Users/u-blox.LATITUDEE7250/Downloads/u-blox-sho-OpenCPU-master/u-blox-sho-OpenCPU-master/NINA-W1-OTP/patches/ubx_phy_cal_esp_idf_4_3.patch -d /c/Users/u-blox.LATITUDEE7250/.platformio/packages/framework-espidf/components
patching file esp_wifi/CMakeLists.txt
Hunk #1 FAILED at 28.
1 out of 1 hunk FAILED -- saving rejects to file esp_wifi/CMakeLists.txt.rej
can't find file to patch at input line 18
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/components/esp_wifi/src/phy_init.c b/components/esp_wifi/src/phy_init.c
|index 0f50000f20..c6665638ce 100644
|--- a/components/esp_wifi/src/phy_init.c
|+++ b/components/esp_wifi/src/phy_init.c
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored

Thanks

**Comment by ldab** [comment]
Patch is only available for IDF 4.0 and IDF 4.3 

https://github.com/u-blox/u-blox-sho-OpenCPU/tree/master/NINA-W1-OTP#esp-idf-40x-and-43x

**Comment by ldab** [comment]
Patch is only available for IDF 4.0 and IDF 4.3

https://github.com/u-blox/u-blox-sho-OpenCPU/tree/master/NINA-W1-OTP#esp-idf-40x-and-43x

IDF 4.4 is expected end of November.

**Comment by ldab** [comment]
I noticed you are using `platformIO`, make sure that the framework used is indeed v4.4.2, until the calibration values are available you can manually patch as described below
```
--- a/components/esp_phy/src/phy_init.c
+++ b/components/esp_phy/src/phy_init.c
@@ -477,11 +477,11 @@ void esp_phy_release_init_data(const esp_phy_init_data_t* init_data)
 
 // phy_init_data.h will declare static 'phy_init_data' variable initialized with default init data
 
-const esp_phy_init_data_t* esp_phy_get_init_data(void)
-{
-    ESP_LOGD(TAG, "loading PHY init data from application binary");
-    return &phy_init_data;
-}
+// const esp_phy_init_data_t* esp_phy_get_init_data(void)
+// {
+//     ESP_LOGD(TAG, "loading PHY init data from application binary");
+//     return &phy_init_data;
+// }
 
 void esp_phy_release_init_data(const esp_phy_init_data_t* init_data)
 {
diff --git a/components/esp_wifi/CMakeLists.txt b/components/esp_wifi/CMakeLists.txt
index 961bcccac7..7ce707be86 100644
--- a/components/esp_wifi/CMakeLists.txt
+++ b/components/esp_wifi/CMakeLists.txt
@@ -31,7 +31,7 @@ idf_component_register(SRCS "${srcs}"
                     INCLUDE_DIRS "include"
                     REQUIRES esp_event esp_phy
                     PRIV_REQUIRES driver esptool_py esp_netif esp_pm esp_timer nvs_flash
-                                  wpa_supplicant hal ${extra_priv_requires}
+                                  wpa_supplicant hal ubx_phy_cal ${extra_priv_requires}
                     LDFRAGMENTS "${ldfragments}")
 
 if(CONFIG_ESP32_WIFI_ENABLED)
```

Keep in mind that a new folder called `components` will need to be created on the project dir.

**Comment by leo-ublox** [comment]
0144d4aa0e9eada3575a47c76127b8eb50041207
