### ISSUE TITLE
Can not build with ubx_evknorab10_nrf5340

### ISSUE THREAD

**Issue by letrthong** [u-blox/u-blox-sho-OpenCPU#13]
Hello All,

Hardware info 
    - Windows 10- 64 bit
    - nFR Connect SDK v2.2.0
     - EVK-NORA-B100-00

i referred guide at 
https://content.u-blox.com/sites/default/files/EVK-NORA-B1_UserGuide_UBX-20030319.pdf at page 25 
"  EVK-NORA-B1 ->the Nordic Semiconductor nRF5340 "

When I selected "ubx_evknorab10_nrf5340" as the guide but could not build with the log as below.
and I pulled code from master branch and copy "ubx_evknorab10_nrf5340" to "C:\v2.2.0\nrf\boards\arm" on  windows OS

  -----------------------------------------------------------------------------------------------------------------------
`'label' is marked as deprecated in 'properties:' in C:/v2.2.0/zephyr/dts/bindings\mtd\nordic,qspi-nor.yaml for node /soc/peripheral@50000000/qspi@2b000/mx25r6435f@0.
-- Generated zephyr.dts: C:/Users/HP/dev/peripheral_lbs/build/zephyr/zephyr.dts
-- Generated devicetree_generated.h: C:/Users/HP/dev/peripheral_lbs/build/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: C:/Users/HP/dev/peripheral_lbs/build/zephyr/dts.cmake

warning: RPMSG_SERVICE_IPM_TX_NAME (defined at C:/v2.2.0/nrf/boards/arm/ubx_evknorab10_nrf5340/Kconfig.defconfig:100) defined without a type

warning: RPMSG_SERVICE_IPM_RX_NAME (defined at C:/v2.2.0/nrf/boards/arm/ubx_evknorab10_nrf5340/Kconfig.defconfig:104) defined without a type

error: Aborting due to Kconfig warnings

Parsing C:/Users/HP/dev/peripheral_lbs/Kconfig
Loaded configuration 'C:/v2.2.0/nrf/boards/arm/ubx_evknorab10_nrf5340/ubx_evknorab10_nrf5340_cpuapp_defconfig'
Merged configuration 'C:/Users/HP/dev/peripheral_lbs/prj.conf'
CMake Error at C:/v2.2.0/zephyr/cmake/modules/kconfig.cmake:328 (message):
  command failed with return code: 1
Call Stack (most recent call first):
  C:/v2.2.0/nrf/cmake/modules/kconfig.cmake:29 (include)
  C:/v2.2.0/zephyr/cmake/modules/zephyr_default.cmake:108 (include)
  C:/v2.2.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  C:/v2.2.0/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:97 (include_boilerplate)
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: 'c:\toolchains\v2.2.0\opt\bin\cmake.EXE' '-DWEST_PYTHON=c:\toolchains\v2.2.0\opt\bin\python.exe' '-Bc:\Users\HP\dev\peripheral_lbs\build' -GNinja '-Sc:\Users\HP\dev\peripheral_lbs'

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. `
 -----------------------------------------------------------------------------------------------------------------------------

**Comment by ghost** [comment]
@letrthong , we are working on an updated set of board files as Zephyr has been updated within the nRF Connect SDK v2.2.0. 

In the meantime, you can use the Nordic DK files. Our EVK-NORA-B1 is equivalent to the nRF5340DK. You can use `nrf5340dk_nrf5340` with the appropriate suffix for the core.

**Comment by letrthong** [comment]
Currently. I  can work nRF SDK v2.0. it is ok

**Comment by dsconyers** [comment]
> @letrthong , we are working on an updated set of board files as Zephyr has been updated within the nRF Connect SDK v2.2.0.
> 
> In the meantime, you can use the Nordic DK files. Our EVK-NORA-B1 is equivalent to the nRF5340DK. You can use `nrf5340dk_nrf5340` with the appropriate suffix for the core.

Is the updated set of board files still work in progress?  Just checking.  Thanks!

**Comment by letrthong** [comment]
Thank you  for your support. let me  check

**Comment by ghost** [comment]
We are still at NCS v2.0.2 for EVK-NORA-B10.

**Comment by ghost** [comment]
EVK-NORA-B10 updated. See https://github.com/u-blox/u-blox-sho-OpenCPU/pull/18.

**Comment by ghost** [comment]
Merged PR with updates.
