### ISSUE TITLE
The `ubx_evknorab12_nrf5340` BSP is NOT included in u-blox-sho-OpenCPU GitHub repository

### ISSUE THREAD

**Issue by dsconyers** [u-blox/u-blox-sho-OpenCPU#17]
I'm following _section 3.2.3_ of the [EVK-NORA-B1 User Guide](https://content.u-blox.com/sites/default/files/EVK-NORA-B1_UserGuide_UBX-20030319.pdf). I have 2 EVK-NORA-B126 boards that I'm trying to provision to evaluate their RF range. I copied the entire `.\zephyr\boards\arm\ubx_evknorab10_nrf5340` folder into the NCS directory `.\ncs\vX.Y.Z\zephyr\boards\arm`, but Visual Studio Code doesn't recognize `ubx_evknorab12_nrf5340_cpuapp` as a valid board (i.e. doesn't show up in drop down list). It recognizes `ubx_evknorab10_nrf5340_cpuapp`, but not the `ubx_evknorab12_nrf5340_cpuapp `(the variant with the integrated Skyworks FEM). See attached screenshot.
![No ubx_evknorab12_nrf5340_cpuapp](https://user-images.githubusercontent.com/39779083/218522946-af0e88a2-f1b4-49f7-b024-1ad3063e3760.JPG)

I then searched the contents of the all the files in the `.\zephyr\boards\arm` directory (including sub-directories) for `ubx_evknorab12_nrf5340` and found no results.

1. Related Products: 
EVK-NORA-B12x Series

2. Pre-setup Conditions:
Obtain any EVK-NORA-B12x board.
3. Reproducibility Rate:
100%
4. Detail Steps to Reproduce:
Follow the instructions starting in section 3 of the [EVK-NORA-B1 User Guide](https://content.u-blox.com/sites/default/files/EVK-NORA-B1_UserGuide_UBX-20030319.pdf) using any EVK-NORA-12x board to attempt to load an NCS sample application.
5. Expected Test Results:
`ubx_evknorab12_nrf5340 `BSP would be included in the [u-blox-sho-OpenCPU GitHub repository](https://github.com/u-blox/u-blox-sho-OpenCPU/tree/master/zephyr/boards/arm).
6. Actual Test Results:
`ubx_evknorab12_nrf5340 `BSP is NOT included in the [u-blox-sho-OpenCPU GitHub repository](https://github.com/u-blox/u-blox-sho-OpenCPU/tree/master/zephyr/boards/arm).

**Comment by ghost** [comment]
The board package `ubx_evknora_b12` is not yet ready for release. In the meantime, Nordic Semiconductor has instructions for adding 2-pin FEM support here: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/app_dev/working_with_fem/index.html#ug-radio-fem-skyworks
It does not seem complete as it only mentions adding a node to the devicetree, but does not list other dependencies. We have opened a ticket with Nordic.

**Comment by dsconyers** [comment]
Hi Bob,

Any update on this?  I'm just curious if anyone at U-blox has successfully loaded a sample application onto an EVK-NORA-B12 that successfully makes use of the FEM to evaluate its range, which is my short term goal.  Thanks!

**Comment by ghost** [comment]
I have it working. I just need to tidy up the files. I'll have something for you later today.

**Comment by ghost** [comment]
Until we have the full BSP ready, you can use the files here with the `nrf5340dk_nrf5340` board. The zip file attached has the `peripheral_lbs` example modified to operate the FEM control pins on NORA-B12. The main files to check are:
- `./boards/nrf5340dk_nrf5340_cpuapp.overlay`
- `./boards/nrf5340dk_nrf5340_cpuappns.overlay`
- `./child_image/hci_rpmsg.conf`
- `./child_image/hci_rpmsg.overlay`
I ran this on both the EVK-NORA-B106 and EVK-NORA-B126. I observed P1.08 and P1.09 toggling as expected. The NORA-B106 does not have the FEM, where NORA-B126 does. I observed approximately 10 dB RSSI difference betwen them when scanning on my iPhone using the nRF Connect mobile app.

Also, please note this SDK errata regarding actual vs. set output power:[ [CONFIG_BT_CTLR_TX_PWR_ANTENNA](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.2.0/kconfig/index.html#CONFIG_BT_CTLR_TX_PWR_ANTENNA)](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/known_issues.html#softdevice-controller)

Project file:
[peripheral_lbs_with_nora-b12_fem_ncs220.zip](https://github.com/u-blox/u-blox-sho-OpenCPU/files/10769910/peripheral_lbs_with_nora-b12_fem_ncs220.zip)

**Comment by dsconyers** [comment]
Hi Bob,

Thanks!  I can see TX_EN & RX_EN toggling as shown below:
![image](https://user-images.githubusercontent.com/39779083/219768918-303c2711-5cc7-42b4-9a13-e6410f8da1a9.png)

![IMG_7606](https://user-images.githubusercontent.com/39779083/219783309-450b9d96-5651-4feb-be9f-c24ac2bdb36b.PNG)

**Comment by ghost** [comment]
EVK-NORA-B12 added. See https://github.com/u-blox/u-blox-sho-OpenCPU/pull/18.

**Comment by ghost** [comment]
Merged PR with updates.
