### ISSUE TITLE
Undefined Kconfig type when building Zephyr

### ISSUE THREAD

**Issue by brian-greeson** [u-blox/u-blox-sho-OpenCPU#20]
Get the following error when attempting to build a zephyr project using the nora b1 board definitions.

``` shell
warning: UART_NRF_DK_SERIAL_WORKAROUND (defined at /apps/my_application/boards/arm/ubx_evknorab10_nrf5340/Kconfig.defconfig:100) defined without a type

error: Aborting due to Kconfig warnings
```

The issue can be resolved by modifying the Kconfig.defconfig file in `/zephyr/boards/arm/ubx_evknorab10_nrf5340/` and `/zephyr/boards/arm/ubx_mininorab10_nrf5340/` 

from:
```
config UART_NRF_DK_SERIAL_WORKAROUND
	default y if ZTEST
```
to:
```
config UART_NRF_DK_SERIAL_WORKAROUND
	bool "Enable nRF DK serial workaround"
	default y if ZTEST
	```

**Comment by perssonmagnus** [comment]
Not valid for new releases, I assume? Closing, reopen if problem still persists.
