### ISSUE TITLE
NINA-W10x OTP patch for ESP-IDF v5.1

### ISSUE THREAD

**Issue by mmt-10** [u-blox/u-blox-sho-OpenCPU#21]
Hi,
When will you release OTP patch for ESP-IDF v5.1?

v4.4 is maintenance and v5.0 will be maintenance from Nov/2023.
So, we should use v5.1 for new design.

[https://github.com/espressif/esp-idf/#esp-idf-release-support-schedule](https://github.com/espressif/esp-idf/#esp-idf-release-support-schedule)

**Comment by mmt-10** [comment]
Hi,
How about this inquiry?
When will you release it?

**Comment by ftor-work** [comment]
Hi @mmt-10,

We are working on it and testing the updates before publishing it on the public repo. 

Possibly, the estimated delivery time is the end of the following week.

Best wishes.

**Comment by mmt-10** [comment]
Hi,
Thank you for your reply.
I understand it.

**Comment by mmt-10** [comment]
Hi, Thank you for your cooperation.

I could apply patch for ESP-IDF v5.1 & v5.1.1.

BTW, verification value is below message.
> W (723) ubx_phy_cal: rf freq calibration enabled, value_otp = -2(ppm), value_set = 1(8kHz)

However, value are different from below URL.
[https://github.com/u-blox/u-blox-sho-OpenCPU/tree/master/NINA-W1-OTP#verifying-patches](https://github.com/u-blox/u-blox-sho-OpenCPU/tree/master/NINA-W1-OTP#verifying-patches)

> value_otp = -1(ppm), value_set = 0(8kHz)

Is it no problem?

**Comment by ftor-work** [comment]
Hello,

These values could be different compared to those shown in the ReadME file.

I updated the code. Please use the newest version in our measurements.

Best wishes.
Fernando

**Comment by mmt-10** [comment]
Hi,

Thank you for your cooperation.
I use ESP-IDF v5.1.1 with your new OTP patch as below.

```
$ git log -1
commit 72dd4395ede9c3b742f364f6985aea55203addab (HEAD -> master, origin/master, origin/HEAD)
Merge: dc0e2b8 eb2e638
Author: Fernando Torres <125648415+ftor-u-blox@users.noreply.github.com>
Date:   Thu Nov 9 21:00:35 2023 +0100

    Merge pull request #23 from u-blox/ftor_nina_w1_otp_5.1
    
    ftor nina w1 otp 5.1
```

However, verification message is different.

(I tried v5.1, however, v5.1 verification message is same result)

> W (718) ubx_phy_cal: rf freq calibration enabled, value_otp = -2(ppm), value_set = 1(8kHz)
> W (728) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration

Please refer to below log.
[ubx.log](https://github.com/u-blox/u-blox-sho-OpenCPU/files/13329541/ubx.log)

My step is as below.
I modified below `CMakeLists.txt` and copied `$OTP_PATCH_PATH/ubx*` to `components` directory.
[https://github.com/espressif/esp-idf/blob/e088c3766ba440e72268b458a68f27b6e7d63986/components/esp_wifi/CMakeLists.txt#L39](https://github.com/espressif/esp-idf/blob/e088c3766ba440e72268b458a68f27b6e7d63986/components/esp_wifi/CMakeLists.txt#L39)
```cmake
39 idf_component_register(SRCS "${srcs}"
40                     INCLUDE_DIRS "include" "wifi_apps/include"
41                     REQUIRES esp_event esp_netif
42                     PRIV_REQUIRES driver esptool_py esp_pm esp_timer nvs_flash esp_phy
43                                   wpa_supplicant hal lwip esp_coex ubx_phy_cal ${extra_priv_requires}
44                     LDFRAGMENTS "${ldfragments}")
```

```bash
~/esp32/esp-idf-v5.1.1-ubx/components$ ls -l ubx*
ubx_otp:
total 31
-rw-rw-r-- 1 mmt-10 mmt-10   985 Nov 13 08:41 CMakeLists.txt
-rw-rw-r-- 1 mmt-10 mmt-10   316 Nov 13 08:41 component.mk
drwxrwxr-x 2 mmt-10 mmt-10     6 Nov 13 08:41 include
-rw-rw-r-- 1 mmt-10 mmt-10     0 Nov 13 08:41 Kconfig.projbuild
-rw-rw-r-- 1 mmt-10 mmt-10  5484 Nov 13 08:41 otp_is25lp.c
-rw-rw-r-- 1 mmt-10 mmt-10  5399 Nov 13 08:41 otp_mx25.c
-rw-rw-r-- 1 mmt-10 mmt-10 12841 Nov 13 08:41 otp_reader.c

ubx_phy_cal:
total 17
-rw-rw-r-- 1 mmt-10 mmt-10  955 Nov 13 08:41 CMakeLists.txt
-rw-rw-r-- 1 mmt-10 mmt-10  316 Nov 13 08:41 component.mk
drwxrwxr-x 2 mmt-10 mmt-10    3 Nov 13 08:41 include
-rw-rw-r-- 1 mmt-10 mmt-10    0 Nov 13 08:41 Kconfig.projbuild
-rw-rw-r-- 1 mmt-10 mmt-10 6609 Nov 13 08:41 ubx_phy_cal.c
```

I copied your example to below `$ESP_IDF/examples/ubx` and run `idf.py build`.

```bash
~/esp32/esp-idf-v5.1.1-ubx/examples/ubx$ ls -l
total 113
drwxrwxr-x  6 mmt-10 mmt-10    13 Nov 13 09:03 ./
drwxrwxr-x 22 mmt-10 mmt-10    23 Nov 13 09:00 ../
drwxrwxr-x  9 mmt-10 mmt-10    36 Nov 13 09:03 build/
-rw-rw-r--  1 mmt-10 mmt-10   686 Nov 13 09:01 CMakeLists.txt
drwxrwxr-x  4 mmt-10 mmt-10     4 Nov 13 09:01 components/
-rw-rw-r--  1 mmt-10 mmt-10 10173 Nov 13 09:01 LICENSE
drwxrwxr-x  2 mmt-10 mmt-10     6 Nov 13 09:01 main/
-rw-rw-r--  1 mmt-10 mmt-10   190 Nov 13 09:01 Makefile
drwxrwxr-x  2 mmt-10 mmt-10     6 Nov 13 09:01 patches/
-rw-rw-r--  1 mmt-10 mmt-10  1644 Nov 13 09:01 README.md
-rw-rw-r--  1 mmt-10 mmt-10 53229 Nov 13 09:03 sdkconfig
-rw-rw-r--  1 mmt-10 mmt-10    68 Nov 13 09:01 sdkconfig.defaults
-rw-rw-r--  1 mmt-10 mmt-10 45140 Nov 13 09:02 sdkconfig.old
```

**Comment by ftor-work** [comment]
Hello,
I didn't get this message. Could you follow the steps shown in the attached video?

`#Clone u-blox Open CPU repo`
`git clone https://github.com/u-blox/u-blox-sho-OpenCPU.git`
`#Go to the NINA folder`
`cd .\u-blox-sho-OpenCPU\NINA-W1-OTP\`
`#Clone esp-idf v5.1.1`
`git clone -b v5.1.1 --recursive https://github.com/espressif/esp-idf.git v5.1.1_release`
`#Go to esp-idf folder`
`cd .\v5.1.1_release\`
`#Apply the patch on v.5.1.1`
`patch -p2 -i C:\gitrepos\u-blox-sho-OpenCPU\NINA-W1-OTP\patches\ubx_phy_cal_esp_idf_5_1.patch -d C:\gitrepos\v5.1.1_release\components`
`#Check the applied patch`
`git status`
`git log`
`git diff e088c3766ba440e72268b458a68f27b6e7d63986`
`#Export esp-idf v5.1.1`
`C:\gitrepos\v5.1.1_release\export.ps1`
`#Set device target`
`idf.py set-target esp32`
`#Add Wi-Fi credentials to the example`
`idf.py menuconfig`
`#Build and flash the code`
`idf.py -p COM88 build flash monitor`

If you still get this message, please open a case on Salesforce. Then, we can check your setup.

Best wishes.
Fernando

https://github.com/u-blox/u-blox-sho-OpenCPU/assets/125648415/f56c802c-f0c4-485b-a01c-08fffd6173d3

**Comment by mmt-10** [comment]
@ftor-u-blox 
Thank you for your reply.
I followed your step with newest commit fe62a574ff37140ea96fb09ebf4de8b2176a7251 again, however, I got message.

> W (706) ubx_phy_cal: rf freq calibration enabled, value_otp = -2(ppm), value_set = 1(8kHz)
> W (716) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration

I understand `value_otp = -2(ppm), value_set = 1(8kHz)` is no problem.
When warning `phy_init: failed to load RF calibration data (0x1102), falling back to full calibration` occurs, what problem will happen?
I would like to know side effect.

Your environment is windows, my environment is ubuntu 22.04.
However, I think it is not root cause...

**Comment by ftor-work** [comment]
Hello.

I found [this discussion](https://esp32.com/viewtopic.php?t=4097) in the Espressif forum and check-in the ESP_Angus comment:
Restarts during full RF calibration are almost always due to power stability (or power supply capacitance) problems.

Maybe, it could be your case.

Cheers.
Fernando

**Comment by ldab** [comment]
> @ftor-u-blox Thank you for your reply. I followed your step with newest commit [fe62a57](https://github.com/u-blox/u-blox-sho-OpenCPU/commit/fe62a574ff37140ea96fb09ebf4de8b2176a7251) again, however, I got message.
> 
> > W (706) ubx_phy_cal: rf freq calibration enabled, value_otp = -2(ppm), value_set = 1(8kHz)
> > W (716) phy_init: failed to load RF calibration data (0x1102), falling back to full calibration
> 
> I understand `value_otp = -2(ppm), value_set = 1(8kHz)` is no problem. When warning `phy_init: failed to load RF calibration data (0x1102), falling back to full calibration` occurs, what problem will happen? I would like to know side effect.
> 
> Your environment is windows, my environment is ubuntu 22.04. However, I think it is not root cause...

The message `phy_init: failed to load RF calibration data (0x1102), falling back to full calibration` is not a problem, full calibration will happen in several instances as mentioned here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/RF_calibration.html#full-calibration

So if that is the first boot, it will calibrate RF and save to NVS (if enabled by `CONFIG_ESP_PHY_CALIBRATION_AND_DATA_STORAGE`).

**Comment by mmt-10** [comment]
@ftor-u-blox and @ldab 

Thank you for your reply.
I understand meaning of warning message.

`phy_init: failed to load RF calibration data (0x1102), falling back to full calibration` did not show after NINA-W106 was rebooted by reset button.
