### ISSUE TITLE
ANNA B402C TX RX Problem

### ISSUE THREAD

**Issue by S0UL4** [u-blox/u-blox-sho-OpenCPU#32]
Hello everyone,

When I use the BLE Peripheral with TX and RX connected to the FT232RL (virtual COM port on my PC), I can see the data that I send to my UART. However, when I type into the PuTTY terminal on the COM port of the FT232RL and send data back, I receive garbage data in my TX Nordic application.

Any help ?

Thanks in advance!

**Comment by perssonmagnus** [comment]
Hello Sir,

Could you tell us a little bit more about what you are doing? Is it this example: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/2.6.0/nrf/samples/bluetooth/peripheral_uart/README.html 

together with the UART application in the nRF toolbox?

Best Regards,
Magnus

**Comment by S0UL4** [comment]
Hello Magnus,
Thanks for your response. It was resolved ! i forget to remove the jumpers on TX and RX to be able to use the UART protocol from the pins  !

**Comment by perssonmagnus** [comment]
Hello,

Great that it got resolved.
