### ISSUE TITLE
Nora B10 Low Frequency Clock Under Hardware Model v2

### ISSUE THREAD

**Issue by Demizo** [u-blox/u-blox-sho-OpenCPU#35]
After Zephyr's move to [hardware model v2](https://github.com/zephyrproject-rtos/zephyr/commit/8dc3f856229ce083c956aa301c31a23e65bd8cd8) the board files for the Nora B10 default to searching for en external low frequency clock source. However, the module does not have one built in.

If using Nordic Connect (NCS version 2.7.0+), this can be fixed by adding `CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y` to the board's `Kconfig.defconfig`. Otherwise the board will idle on boot waiting for a non-existent external low frequency clock.

**Comment by perssonmagnus** [comment]
Hi,

There will shortly be an effort to move the Zephyr board definitions in this repo to the hardware model v2. 

Regarding the NORA-B10 definition and the 32 kHz crystal note that the board definitions are for EVK-NORA-B1, which does have a 32 kHz crystal on the board, but as you say not in the actual module. Refer to the [EVK-NORA-B1 user guide](https://content.u-blox.com/sites/default/files/EVK-NORA-B1_UserGuide_UBX-20030319.pdf) for more information.

Best Regards,
Magnus

**Comment by Demizo** [comment]
Thank you,

As you point out, it makes sense to use of the external clock source on the evaluation board. Given that, I'll close this issue since there is no action to be taken. It is unfortunate that my board misconfiguration was silently fixed by defaults prior to NCS 2.7.0. Hopefully if someone has a similar issue they will find this.
