### ISSUE TITLE
Logging not working on network core for ubx_evknorab10_nrf5340

### ISSUE THREAD

**Issue by marchaesen** [u-blox/u-blox-sho-OpenCPU#4]
Logging is not working for board ubx_evknorab10_nrf5340 because the wrong pin numbers for uarte are specified in zephyr/boards/arm/ubx_evknorab10_nrf5340/nrf5340_cpunet_reset.c

#define CPUNET_UARTE_PIN_TX  33
#define CPUNET_UARTE_PIN_RX  32

should be

#define CPUNET_UARTE_PIN_TX  1
#define CPUNET_UARTE_PIN_RX  0

After this change, logging on the network core is working.

**Comment by ghost** [comment]
We are working on updating these files to be compatible with NCS v2.0.0. They were last released around the time of v1.6.1.

**Comment by ghost** [comment]
ubx_evknorab10_nrf5340 has been updated based on nrf5340dk_nrf5340 for NCS v2.0.2 (identical files in v2.0.0 and v2.0.1). Network core logging appears to be working now.
